name: Recipe List CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build :
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        env:
          ci: true
          ATLAS_URI: ${{ secrets.ATLAS_LAMBDA_URI }}

      - name: Set-up node
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"
      - run: npm ci

  deploy :
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        env:
          ci: true
          ATLAS_URI: ${{ secrets.ATLAS_LAMBDA_URI }}

      - name: Heroku Data
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hf-recipe-app"
          heroku_email: "eshwarkalyan78@gmail.com"
