name: Recipe List CI
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-up node
        uses: actions/setup-node@v1
        with:
          node-version: "17.x"
      - run: npm install
      - run: node server.js